# ~/.config/scooter/config.toml

[editor_open]
command = "hx %file:%line"
exit = true

[preview]
syntax_highlighting = true
syntax_highlighting_theme = "Catppuccin Mocha"

[style]
true_color = true
wrap_text = false

[search]
disable_prepopulated_fields = false
